Gap filling
CMBSciPol/furax pull request #4
Opened 2024-12-02 16:39 UTC by sbiquard

2024-12-09 14:01 UTC, pchanial requested changes

2024-12-09 14:01 UTC, pchanial commented on src/furax/detectors.py
> +        names = reduce(lambda a, b: a + '_' + b, det_indices, 'FAKE_DET')
On pourraitremplir avec des 0:
```suggestion
        widths = [len(str(s - 1)) for s in self.shape]
        indices = [[f'{index:0{width}}' for index in range(dim)] for dim, width in zip(self.shape, widths)]
        names = reduce(lambda a, b: a + '_' + b, indices, 'DET')
```

2024-12-09 14:01 UTC, pchanial commented on src/furax/detectors.py
> +    def split_key(self, key: PRNGKeyArray) -> Shaped[PRNGKeyArray, ' _']:
Pour respecter le sens de lecture de haut en bas, mieux vaut mettre les méthodes appelantes en premier, et donc mettre les méthodes publiques en premier (après les dunders).

2024-12-09 14:01 UTC, pchanial commented on src/furax/detectors.py
> +        """Folds the detector names in a random key to generate a key array."""
```suggestion
        """Produces a new pseudo-random key for each detector."""
```

2024-12-09 14:01 UTC, pchanial commented on src/furax/detectors.py
> +class FakeDetectorArray(DetectorArray):
Déplacer cette classe dans les tests.

2024-12-09 14:01 UTC, pchanial commented on src/furax/preprocessing/gap_filling.py
> +    """Class for filling masked time samples with a constrained noise realization.
+ de détails sur la méthode et donner un exemple.

2024-12-09 14:01 UTC, pchanial commented on src/furax/preprocessing/gap_filling.py
> +    def get_kernel(n_tt: Float[Array, ' _'], size: int) -> Float[Array, ' {size}']:
-> `_get_kernel`

2024-12-09 14:01 UTC, pchanial commented on pyproject.toml
> +authors = [{ name = 'Pierre Chanial', email = 'chanial@apc.in2p3.fr' }]
Il faut t'ajouter dans les auteurs.

2024-12-10 16:58 UTC, sbiquard commented on src/furax/detectors.py
> +        names = reduce(lambda a, b: a + '_' + b, det_indices, 'FAKE_DET')
Great suggestion, done in https://github.com/CMBSciPol/furax/pull/4/commits/90edb4340546e8adbf819b18a5634f89b2e6953f

2024-12-10 16:59 UTC, sbiquard commented on src/furax/detectors.py
> +    def split_key(self, key: PRNGKeyArray) -> Shaped[PRNGKeyArray, ' _']:
Done in https://github.com/CMBSciPol/furax/pull/4/commits/90edb4340546e8adbf819b18a5634f89b2e6953f

2024-12-10 16:59 UTC, sbiquard commented on src/furax/detectors.py
> +        """Folds the detector names in a random key to generate a key array."""
Also done in https://github.com/CMBSciPol/furax/pull/4/commits/90edb4340546e8adbf819b18a5634f89b2e6953f

2024-12-10 16:59 UTC, sbiquard commented on src/furax/detectors.py
> +class FakeDetectorArray(DetectorArray):
Makes sense, done in https://github.com/CMBSciPol/furax/pull/4/commits/90edb4340546e8adbf819b18a5634f89b2e6953f

2024-12-11 07:45 UTC, sbiquard commented on src/furax/preprocessing/gap_filling.py
> +    def get_kernel(n_tt: Float[Array, ' _'], size: int) -> Float[Array, ' {size}']:
Done in https://github.com/CMBSciPol/furax/pull/4/commits/28ddaa7aff1951cdc531341688c6423773204705

2024-12-11 09:04 UTC, sbiquard commented on src/furax/preprocessing/gap_filling.py
> +    """Class for filling masked time samples with a constrained noise realization.
See https://github.com/CMBSciPol/furax/pull/4/commits/668be101160e0c8bf71cf1deb7c49ba9b1b5ab1a

2024-12-11 09:13 UTC, merged